### ISSUE TITLE
Algorand Blockchain

### ISSUE THREAD

**Issue by Daudaopeyemi7** [ChoiceCoin/Voting#512]
A good and amazing project with better rewards.
This is gonna b a big project on Algorand Blockchain .

Let go the moon🚀🚀🚀AYYCQP5WNFKON4HQ4YN32KWJZXGBLT73R5HTQNXR24OKUQTJDXNPTQDIXA

**Comment by Aigithu** [comment]
ChoiceCoin Bridging the Decentralized Governance Problem. 
Choice Coin as an open source digital asset is used to solve the decentralized governance problem. Due to the complex process by which assets are allocated across decentralized networks there is a lack in the systems method to facilitate autonomous decision making in a distributed manner using digital assets. Choice Coin solves the decentralized governance problem by providing a mechanism for secure voting using post-quantum cryptography. A voting token for autonomous organizations, Choice Coin is built on the Algorand blockchain as an Algorand Standard Asset.

The goal for the Choice Coin Community is to support the Algorand Community in growing an open, collaborative, and borderless blockchain. Thus, the Choice Coin Network is intrinsically designed to draw new members and retain existing members on the Algorand Network through an optimized participation structure. There are three main methods for participation in the Choice Coin ecosystem. The three main participation options are democratic involvement incentives, charitable contributions, and open innovation. Additionally, Choice Coin’s inclusive strategy may be amended to include more participation options over time and is focused toward creating new value on the Algorand Network.
